import { Fragment, type ReactNode } from "react";

interface AnswerViewProps {
  answer: string | null;
  highlightTokens: string[];
  isStreaming?: boolean;
}

function renderWithHighlights(answer: string, highlights: string[]): ReactNode {
  if (!highlights.length) return answer;
  const parts: ReactNode[] = [];
  let rest = answer;
  let key = 0;
  for (const phrase of highlights) {
    if (!phrase) continue;
    const i = rest.indexOf(phrase);
    if (i === -1) continue;
    if (i > 0) parts.push(<Fragment key={`t-${key++}`}>{rest.slice(0, i)}</Fragment>);
    parts.push(
      <mark
        key={`h-${key++}`}
        className="bg-sky-100/90 text-sky-900 rounded px-0.5 font-medium not-italic"
      >
        {phrase}
      </mark>
    );
    rest = rest.slice(i + phrase.length);
  }
  if (rest) parts.push(<Fragment key={`t-${key++}`}>{rest}</Fragment>);
  return parts.length ? <>{parts}</> : answer;
}

/** Hero “best-fit” answer with optional emphasis on 1–2 decision tokens. */
export default function AnswerView({ answer, highlightTokens, isStreaming }: AnswerViewProps) {
  if (!answer && !isStreaming) {
    return (
      <p className="text-gray-400 text-sm leading-relaxed">
        Run a question to see the model&apos;s best-fit answer.
      </p>
    );
  }
  return (
    <div className="space-y-3">
      <h2 className="text-xs font-semibold text-gray-500 uppercase tracking-wide">
        Best-fit answer
      </h2>
      <p className="text-2xl sm:text-3xl font-light text-gray-900 leading-snug tracking-tight whitespace-pre-wrap">
        {answer ? renderWithHighlights(answer, highlightTokens) : null}
        {isStreaming && (
          <span className="inline-block w-2 h-6 ml-1 align-middle bg-gray-300 animate-pulse rounded-sm" />
        )}
      </p>
      <p className="text-sm text-gray-500 max-w-2xl">
        Generated by selecting the highest-probability (&lsquo;best-fit&rsquo;) word at each step.
      </p>
    </div>
  );
}
