/** Auto-generated by scripts/capture-evaluation.mjs — run again after model/backend changes. */
export const EVALUATION_CAPTURED_AT_ISO = "2026-03-30T12:06:50.721Z";
export const CAPTURED_SAMPLING = { temperature: 0.5, top_p: 0.9, max_tokens: 384 } as const;

export const CAPTURED_RESPONSES: readonly string[] = [
  "The flaw is in treating one fact as conclusive. Inference must allow for alternatives and demand corroboration., leading inevitably to the conclusion that Sound reasoning keeps conjecture distinct from demonstration.\n",
  "The circumstance that Holmes glanced at me and raised his eyebrows sardonically. gives us a limited but useful starting point. We must then test what it implies about means, opportunity, or character.. It is enough to guide our next step, and no more.\n",
  "\"It is in “Here is your ring, Mrs., Watson, that the whole affair turns.\", Watson, that we shall find the clue.\"\nSecond, We must see what it implies before we decide anything.\n",
  "I am Sherlock Holmes, consulting detective of Baker Street. My profession is to observe what others overlook.\nSecond, My method is to ask what seems obvious, then test the facts.\n",
  "The circumstance that the fall of the Roman Empire is well known to history gives us a limited but useful starting point. We must then test what that implies about the means or the opportunity.\nSecond, For the moment it narrows our view, but the evidence will wear away.\n",
  "The facts lead us somewhere definite: The answer lies in a small observation: The clue suggests a direction, but the case must be built on more than suggestion.\nSecond, We must see how it stands before we decide anything.\n",
];
