/** Auto-generated by scripts/capture-evaluation.mjs — run again after model/backend changes. */
export const EVALUATION_CAPTURED_AT_ISO = "2026-03-30T22:35:10.280Z";
export const CAPTURED_SAMPLING = { temperature: 0.5, top_p: 0.9, max_tokens: 384 } as const;

export const CAPTURED_RESPONSES: readonly string[] = [
  "It is unsound to leap from one detail to guilt. We may entertain several hypotheses; none amounts to proof.\nSecond, Only then does the conclusion become defensible.\n",
  "From Holmes glanced at me and raised his eyebrows sardonically. we obtain a clue to habits, recent movements, or character, rather than a full explanation.\nSecond, It points to a hypothesis which must be tried and either confirmed or discarded.\n",
  "\"The key lies in the following detail, Watson: \"You have seen the same thing, Watson: “Here is your ring, Mrs.”. The difference is in the inference.\", leading inevitably to the conclusion that We must see what it implies before we decide anything.\n",
  "I am Sherlock Holmes, consulting detective of Baker Street. My profession is to observe what others overlook.\nSecond, My method is to gather the facts in a straightforward and deductive manner.\n",
  "The circumstance that the fall of the Roman Empire is well known gives us a limited but useful starting point. We must then test what that implies about the means or the opportunity.\nSecond, The conclusion follows when we weigh it against other facts.\n",
  "The key lies in the following detail: The clue to the mystery is in The antibiotic is used to treat bacterial infections.\nSecond, We must see how it stands before we decide anything.\n",
  "What we have is this: one word or short phrase only. The second letter is a very special one. It is the letter A, which is the first letter of... We must see whether the other hints agree.\nSecond, We should test this hint against the rest of the evidence before ruling anything out.\n",
  "The conclusion rests on a simple point: The war ended in Europe in 1945.\nSecond, We must see what details affect the conclusion.\n",
  "What we have is this: In one sentence, what is photosynthesis?.. One may infer from it what is more generally observed., leading inevitably to the conclusion that It points to a hypothesis which must be tried and either confirmed or discarded.\n",
  "The facts lead us somewhere definite: The three branches of the United States federal government are the legislative, executive, and judicial.\nSecond, It is enough to guide our next step, and no more.\n",
  "A practiced mind would notice: What we have is this: approximately how fast does light travel in vacuum (in m/s)? One number.... One may infer from it a good deal about the person or the situation.\nSecond, Let the facts accumulate; the truth will out.\n",
];
